# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.api_api import ApiApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.api_api.ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sessions_invalidation(self):
        """Test case for create_sessions_invalidation

        """
        pass

    def test_create_sessions_rekey_item(self):
        """Test case for create_sessions_rekey_item

        """
        pass

    def test_delete_sessions_invalidation(self):
        """Test case for delete_sessions_invalidation

        """
        pass

    def test_get_sessions_invalidation(self):
        """Test case for get_sessions_invalidation

        """
        pass

    def test_get_settings_sessions(self):
        """Test case for get_settings_sessions

        """
        pass

    def test_list_sessions_invalidations(self):
        """Test case for list_sessions_invalidations

        """
        pass

    def test_update_sessions_invalidation(self):
        """Test case for update_sessions_invalidation

        """
        pass

    def test_update_settings_sessions(self):
        """Test case for update_settings_sessions

        """
        pass


if __name__ == '__main__':
    unittest.main()
