# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.catalog_api import CatalogApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_catalog_list(self):
        """Test case for get_catalog_list

        """
        pass

    def test_get_catalog_readme(self):
        """Test case for get_catalog_readme

        """
        pass

    def test_get_catalog_verify(self):
        """Test case for get_catalog_verify

        """
        pass

    def test_update_catalog_clean(self):
        """Test case for update_catalog_clean

        """
        pass

    def test_update_catalog_export(self):
        """Test case for update_catalog_export

        """
        pass

    def test_update_catalog_import(self):
        """Test case for update_catalog_import

        """
        pass

    def test_update_catalog_remove(self):
        """Test case for update_catalog_remove

        """
        pass

    def test_update_catalog_repair(self):
        """Test case for update_catalog_repair

        """
        pass


if __name__ == '__main__':
    unittest.main()
