# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.avscan_nodes_api import AvscanNodesApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestAvscanNodesApi(unittest.TestCase):
    """AvscanNodesApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.avscan_nodes_api.AvscanNodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_node_status(self):
        """Test case for get_node_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
