# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.config_catalog_api import ConfigCatalogApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestConfigCatalogApi(unittest.TestCase):
    """ConfigCatalogApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.config_catalog_api.ConfigCatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config_catalog_status(self):
        """Test case for get_config_catalog_status

        """
        pass

    def test_update_config_catalog_status(self):
        """Test case for update_config_catalog_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
