# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.performance_settings_settings_cpu_limit_us_health_modifier_impact_high import PerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh  # noqa: E501
from isi_sdk.rest import ApiException


class TestPerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh(unittest.TestCase):
    """PerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh(self):
        """Test PerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.performance_settings_settings_cpu_limit_us_health_modifier_impact_high.PerformanceSettingsSettingsCpuLimitUsHealthModifierImpactHigh()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
