# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.settings_sessions_settings import SettingsSessionsSettings  # noqa: E501
from isi_sdk.rest import ApiException


class TestSettingsSessionsSettings(unittest.TestCase):
    """SettingsSessionsSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsSessionsSettings(self):
        """Test SettingsSessionsSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.settings_sessions_settings.SettingsSessionsSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
