# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.cluster_mode_settings_extended import ClusterModeSettingsExtended  # noqa: E501
from isi_sdk.rest import ApiException


class TestClusterModeSettingsExtended(unittest.TestCase):
    """ClusterModeSettingsExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterModeSettingsExtended(self):
        """Test ClusterModeSettingsExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.cluster_mode_settings_extended.ClusterModeSettingsExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
