# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.filepool_policy_action_extended_extended import FilepoolPolicyActionExtendedExtended  # noqa: E501
from isi_sdk.rest import ApiException


class TestFilepoolPolicyActionExtendedExtended(unittest.TestCase):
    """FilepoolPolicyActionExtendedExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilepoolPolicyActionExtendedExtended(self):
        """Test FilepoolPolicyActionExtendedExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.filepool_policy_action_extended_extended.FilepoolPolicyActionExtendedExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
