# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.datamover_policies_api import DatamoverPoliciesApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestDatamoverPoliciesApi(unittest.TestCase):
    """DatamoverPoliciesApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.datamover_policies_api.DatamoverPoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_policy_last_job(self):
        """Test case for get_policy_last_job

        """
        pass


if __name__ == '__main__':
    unittest.main()
