# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.papi_api import PapiApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestPapiApi(unittest.TestCase):
    """PapiApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.papi_api.PapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_papi_settings(self):
        """Test case for get_papi_settings

        """
        pass

    def test_update_papi_settings(self):
        """Test case for update_papi_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
