# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.keymanager_api import KeymanagerApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestKeymanagerApi(unittest.TestCase):
    """KeymanagerApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.keymanager_api.KeymanagerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cluster_rekey_item(self):
        """Test case for create_cluster_rekey_item

        """
        pass

    def test_create_kmip_server(self):
        """Test case for create_kmip_server

        """
        pass

    def test_create_kmip_server_verify_item(self):
        """Test case for create_kmip_server_verify_item

        """
        pass

    def test_create_sed_migrate_item(self):
        """Test case for create_sed_migrate_item

        """
        pass

    def test_create_sed_rekey_item(self):
        """Test case for create_sed_rekey_item

        """
        pass

    def test_delete_kmip_server(self):
        """Test case for delete_kmip_server

        """
        pass

    def test_get_cluster_status(self):
        """Test case for get_cluster_status

        """
        pass

    def test_get_keymanager_cluster(self):
        """Test case for get_keymanager_cluster

        """
        pass

    def test_get_kmip_server(self):
        """Test case for get_kmip_server

        """
        pass

    def test_get_sed_settings(self):
        """Test case for get_sed_settings

        """
        pass

    def test_get_sed_status(self):
        """Test case for get_sed_status

        """
        pass

    def test_get_sed_status_lnn(self):
        """Test case for get_sed_status_lnn

        """
        pass

    def test_list_cluster_rekey(self):
        """Test case for list_cluster_rekey

        """
        pass

    def test_list_kmip_servers(self):
        """Test case for list_kmip_servers

        """
        pass

    def test_list_sed_rekey(self):
        """Test case for list_sed_rekey

        """
        pass

    def test_update_cluster_rekey(self):
        """Test case for update_cluster_rekey

        """
        pass

    def test_update_kmip_server(self):
        """Test case for update_kmip_server

        """
        pass

    def test_update_sed_rekey(self):
        """Test case for update_sed_rekey

        """
        pass

    def test_update_sed_settings(self):
        """Test case for update_sed_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
