# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.create_oauth_oauth2_token_exchange_response import CreateOauthOauth2TokenExchangeResponse  # noqa: E501
from isi_sdk.rest import ApiException


class TestCreateOauthOauth2TokenExchangeResponse(unittest.TestCase):
    """CreateOauthOauth2TokenExchangeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOauthOauth2TokenExchangeResponse(self):
        """Test CreateOauthOauth2TokenExchangeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.create_oauth_oauth2_token_exchange_response.CreateOauthOauth2TokenExchangeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
