# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.providers_saml_services_sp_signing_key_settings_settings_certificate import ProvidersSamlServicesSpSigningKeySettingsSettingsCertificate  # noqa: E501
from isi_sdk.rest import ApiException


class TestProvidersSamlServicesSpSigningKeySettingsSettingsCertificate(unittest.TestCase):
    """ProvidersSamlServicesSpSigningKeySettingsSettingsCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvidersSamlServicesSpSigningKeySettingsSettingsCertificate(self):
        """Test ProvidersSamlServicesSpSigningKeySettingsSettingsCertificate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.providers_saml_services_sp_signing_key_settings_settings_certificate.ProvidersSamlServicesSpSigningKeySettingsSettingsCertificate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
