# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.mapping_users_rules_rules_parameters_default_unix_user import MappingUsersRulesRulesParametersDefaultUnixUser  # noqa: E501
from isi_sdk.rest import ApiException


class TestMappingUsersRulesRulesParametersDefaultUnixUser(unittest.TestCase):
    """MappingUsersRulesRulesParametersDefaultUnixUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMappingUsersRulesRulesParametersDefaultUnixUser(self):
        """Test MappingUsersRulesRulesParametersDefaultUnixUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.mapping_users_rules_rules_parameters_default_unix_user.MappingUsersRulesRulesParametersDefaultUnixUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
