# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.datamover_api import DatamoverApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestDatamoverApi(unittest.TestCase):
    """DatamoverApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.datamover_api.DatamoverApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_certificates_ca_item(self):
        """Test case for create_certificates_ca_item

        """
        pass

    def test_create_certificates_identity_item(self):
        """Test case for create_certificates_identity_item

        """
        pass

    def test_create_datamover_account(self):
        """Test case for create_datamover_account

        """
        pass

    def test_create_datamover_base_policy(self):
        """Test case for create_datamover_base_policy

        """
        pass

    def test_create_datamover_policy(self):
        """Test case for create_datamover_policy

        """
        pass

    def test_create_throttling_bw_rule(self):
        """Test case for create_throttling_bw_rule

        """
        pass

    def test_delete_certificates_ca_by_id(self):
        """Test case for delete_certificates_ca_by_id

        """
        pass

    def test_delete_certificates_identity_by_id(self):
        """Test case for delete_certificates_identity_by_id

        """
        pass

    def test_delete_datamover_account(self):
        """Test case for delete_datamover_account

        """
        pass

    def test_delete_datamover_base_policy(self):
        """Test case for delete_datamover_base_policy

        """
        pass

    def test_delete_datamover_historical_jobs(self):
        """Test case for delete_datamover_historical_jobs

        """
        pass

    def test_delete_datamover_policy(self):
        """Test case for delete_datamover_policy

        """
        pass

    def test_delete_datamover_reports(self):
        """Test case for delete_datamover_reports

        """
        pass

    def test_delete_throttling_bw_rule(self):
        """Test case for delete_throttling_bw_rule

        """
        pass

    def test_get_certificates_ca_by_id(self):
        """Test case for get_certificates_ca_by_id

        """
        pass

    def test_get_certificates_identity_by_id(self):
        """Test case for get_certificates_identity_by_id

        """
        pass

    def test_get_certificates_settings(self):
        """Test case for get_certificates_settings

        """
        pass

    def test_get_config_namespace_by_id(self):
        """Test case for get_config_namespace_by_id

        """
        pass

    def test_get_datamover_account(self):
        """Test case for get_datamover_account

        """
        pass

    def test_get_datamover_base_policy(self):
        """Test case for get_datamover_base_policy

        """
        pass

    def test_get_datamover_config(self):
        """Test case for get_datamover_config

        """
        pass

    def test_get_datamover_config_namespace(self):
        """Test case for get_datamover_config_namespace

        """
        pass

    def test_get_datamover_dataset(self):
        """Test case for get_datamover_dataset

        """
        pass

    def test_get_datamover_datasets(self):
        """Test case for get_datamover_datasets

        """
        pass

    def test_get_datamover_historical_jobs(self):
        """Test case for get_datamover_historical_jobs

        """
        pass

    def test_get_datamover_job(self):
        """Test case for get_datamover_job

        """
        pass

    def test_get_datamover_jobs(self):
        """Test case for get_datamover_jobs

        """
        pass

    def test_get_datamover_policy(self):
        """Test case for get_datamover_policy

        """
        pass

    def test_get_datamover_report(self):
        """Test case for get_datamover_report

        """
        pass

    def test_get_datamover_reports(self):
        """Test case for get_datamover_reports

        """
        pass

    def test_get_network_discover_accid(self):
        """Test case for get_network_discover_accid

        """
        pass

    def test_get_network_ping_accid(self):
        """Test case for get_network_ping_accid

        """
        pass

    def test_get_settings_reports(self):
        """Test case for get_settings_reports

        """
        pass

    def test_get_throttling_bw_rule(self):
        """Test case for get_throttling_bw_rule

        """
        pass

    def test_get_throttling_settings(self):
        """Test case for get_throttling_settings

        """
        pass

    def test_list_certificates_ca(self):
        """Test case for list_certificates_ca

        """
        pass

    def test_list_certificates_identity(self):
        """Test case for list_certificates_identity

        """
        pass

    def test_list_datamover_accounts(self):
        """Test case for list_datamover_accounts

        """
        pass

    def test_list_datamover_base_policies(self):
        """Test case for list_datamover_base_policies

        """
        pass

    def test_list_datamover_policies(self):
        """Test case for list_datamover_policies

        """
        pass

    def test_list_throttling_bw_rules(self):
        """Test case for list_throttling_bw_rules

        """
        pass

    def test_update_certificates_ca_by_id(self):
        """Test case for update_certificates_ca_by_id

        """
        pass

    def test_update_certificates_identity_by_id(self):
        """Test case for update_certificates_identity_by_id

        """
        pass

    def test_update_certificates_settings(self):
        """Test case for update_certificates_settings

        """
        pass

    def test_update_config_namespace_by_id(self):
        """Test case for update_config_namespace_by_id

        """
        pass

    def test_update_datamover_account(self):
        """Test case for update_datamover_account

        """
        pass

    def test_update_datamover_base_policy(self):
        """Test case for update_datamover_base_policy

        """
        pass

    def test_update_datamover_job(self):
        """Test case for update_datamover_job

        """
        pass

    def test_update_datamover_policy(self):
        """Test case for update_datamover_policy

        """
        pass

    def test_update_settings_reports(self):
        """Test case for update_settings_reports

        """
        pass

    def test_update_throttling_bw_rule(self):
        """Test case for update_throttling_bw_rule

        """
        pass

    def test_update_throttling_settings(self):
        """Test case for update_throttling_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
