# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.http_settings_extended import HttpSettingsExtended  # noqa: E501
from isi_sdk.rest import ApiException


class TestHttpSettingsExtended(unittest.TestCase):
    """HttpSettingsExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpSettingsExtended(self):
        """Test HttpSettingsExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.http_settings_extended.HttpSettingsExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
