# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.metadataiq_api import MetadataiqApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestMetadataiqApi(unittest.TestCase):
    """MetadataiqApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.metadataiq_api.MetadataiqApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_metadataiq_reset_item(self):
        """Test case for create_metadataiq_reset_item

        """
        pass

    def test_delete_metadataiq_reset(self):
        """Test case for delete_metadataiq_reset

        """
        pass

    def test_get_metadataiq_certificate(self):
        """Test case for get_metadataiq_certificate

        """
        pass

    def test_get_metadataiq_settings(self):
        """Test case for get_metadataiq_settings

        """
        pass

    def test_get_metadataiq_status(self):
        """Test case for get_metadataiq_status

        """
        pass

    def test_update_metadataiq_settings(self):
        """Test case for update_metadataiq_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
