# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.quota_quotas_summary_summary import QuotaQuotasSummarySummary  # noqa: E501
from isi_sdk.rest import ApiException


class TestQuotaQuotasSummarySummary(unittest.TestCase):
    """QuotaQuotasSummarySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuotaQuotasSummarySummary(self):
        """Test QuotaQuotasSummarySummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.quota_quotas_summary_summary.QuotaQuotasSummarySummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
