# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.datamover_policy_policy_specific_attr_expiration_policy_extended import DatamoverPolicyPolicySpecificAttrExpirationPolicyExtended  # noqa: E501
from isi_sdk.rest import ApiException


class TestDatamoverPolicyPolicySpecificAttrExpirationPolicyExtended(unittest.TestCase):
    """DatamoverPolicyPolicySpecificAttrExpirationPolicyExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatamoverPolicyPolicySpecificAttrExpirationPolicyExtended(self):
        """Test DatamoverPolicyPolicySpecificAttrExpirationPolicyExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.datamover_policy_policy_specific_attr_expiration_policy_extended.DatamoverPolicyPolicySpecificAttrExpirationPolicyExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
