# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.network_api import NetworkApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.network_api.NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dnscache_flush_item(self):
        """Test case for create_dnscache_flush_item

        """
        pass

    def test_create_firewall_policy(self):
        """Test case for create_firewall_policy

        """
        pass

    def test_create_firewall_reset_dscp_setting_item(self):
        """Test case for create_firewall_reset_dscp_setting_item

        """
        pass

    def test_create_firewall_reset_global_policy_item(self):
        """Test case for create_firewall_reset_global_policy_item

        """
        pass

    def test_create_network_groupnet(self):
        """Test case for create_network_groupnet

        """
        pass

    def test_create_network_sc_rebalance_all_item(self):
        """Test case for create_network_sc_rebalance_all_item

        """
        pass

    def test_delete_firewall_policy(self):
        """Test case for delete_firewall_policy

        """
        pass

    def test_delete_network_groupnet(self):
        """Test case for delete_network_groupnet

        """
        pass

    def test_get_firewall_dscp(self):
        """Test case for get_firewall_dscp

        """
        pass

    def test_get_firewall_dscp_rule(self):
        """Test case for get_firewall_dscp_rule

        """
        pass

    def test_get_firewall_policy(self):
        """Test case for get_firewall_policy

        """
        pass

    def test_get_firewall_rules(self):
        """Test case for get_firewall_rules

        """
        pass

    def test_get_firewall_services(self):
        """Test case for get_firewall_services

        """
        pass

    def test_get_firewall_settings(self):
        """Test case for get_firewall_settings

        """
        pass

    def test_get_network_dnscache(self):
        """Test case for get_network_dnscache

        """
        pass

    def test_get_network_external(self):
        """Test case for get_network_external

        """
        pass

    def test_get_network_groupnet(self):
        """Test case for get_network_groupnet

        """
        pass

    def test_get_network_interface_names(self):
        """Test case for get_network_interface_names

        """
        pass

    def test_get_network_interfaces(self):
        """Test case for get_network_interfaces

        """
        pass

    def test_get_network_pools(self):
        """Test case for get_network_pools

        """
        pass

    def test_get_network_rules(self):
        """Test case for get_network_rules

        """
        pass

    def test_get_network_subnets(self):
        """Test case for get_network_subnets

        """
        pass

    def test_list_firewall_policies(self):
        """Test case for list_firewall_policies

        """
        pass

    def test_list_network_groupnets(self):
        """Test case for list_network_groupnets

        """
        pass

    def test_update_firewall_dscp_rule(self):
        """Test case for update_firewall_dscp_rule

        """
        pass

    def test_update_firewall_policy(self):
        """Test case for update_firewall_policy

        """
        pass

    def test_update_firewall_settings(self):
        """Test case for update_firewall_settings

        """
        pass

    def test_update_network_dnscache(self):
        """Test case for update_network_dnscache

        """
        pass

    def test_update_network_external(self):
        """Test case for update_network_external

        """
        pass

    def test_update_network_groupnet(self):
        """Test case for update_network_groupnet

        """
        pass


if __name__ == '__main__':
    unittest.main()
