# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.lfn_api import LfnApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestLfnApi(unittest.TestCase):
    """LfnApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.lfn_api.LfnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_lfn_item(self):
        """Test case for create_lfn_item

        """
        pass

    def test_delete_lfn(self):
        """Test case for delete_lfn

        """
        pass

    def test_delete_lfn_path(self):
        """Test case for delete_lfn_path

        """
        pass

    def test_get_lfn_path(self):
        """Test case for get_lfn_path

        """
        pass

    def test_list_lfn(self):
        """Test case for list_lfn

        """
        pass

    def test_update_lfn_path(self):
        """Test case for update_lfn_path

        """
        pass


if __name__ == '__main__':
    unittest.main()
