# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.supportassist_api import SupportassistApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestSupportassistApi(unittest.TestCase):
    """SupportassistApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.supportassist_api.SupportassistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_supportassist_data_item(self):
        """Test case for create_supportassist_data_item

        """
        pass

    def test_create_supportassist_payload_item(self):
        """Test case for create_supportassist_payload_item

        """
        pass

    def test_create_supportassist_task_item(self):
        """Test case for create_supportassist_task_item

        """
        pass

    def test_delete_supportassist_task_by_id(self):
        """Test case for delete_supportassist_task_by_id

        """
        pass

    def test_get_supportassist_license(self):
        """Test case for get_supportassist_license

        """
        pass

    def test_get_supportassist_settings(self):
        """Test case for get_supportassist_settings

        """
        pass

    def test_get_supportassist_status(self):
        """Test case for get_supportassist_status

        """
        pass

    def test_get_supportassist_task_by_id(self):
        """Test case for get_supportassist_task_by_id

        """
        pass

    def test_get_supportassist_terms(self):
        """Test case for get_supportassist_terms

        """
        pass

    def test_list_supportassist_task(self):
        """Test case for list_supportassist_task

        """
        pass

    def test_update_supportassist_settings(self):
        """Test case for update_supportassist_settings

        """
        pass

    def test_update_supportassist_status(self):
        """Test case for update_supportassist_status

        """
        pass

    def test_update_supportassist_terms(self):
        """Test case for update_supportassist_terms

        """
        pass


if __name__ == '__main__':
    unittest.main()
