# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.local_api import LocalApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestLocalApi(unittest.TestCase):
    """LocalApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.local_api.LocalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cluster_time(self):
        """Test case for get_cluster_time

        """
        pass

    def test_get_network_interfaces(self):
        """Test case for get_network_interfaces

        """
        pass

    def test_get_protocols_smb_sessions(self):
        """Test case for get_protocols_smb_sessions

        """
        pass

    def test_get_upgrade_cluster_firmware_device(self):
        """Test case for get_upgrade_cluster_firmware_device

        """
        pass

    def test_get_upgrade_cluster_firmware_status(self):
        """Test case for get_upgrade_cluster_firmware_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
