# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.connectivity_api import ConnectivityApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestConnectivityApi(unittest.TestCase):
    """ConnectivityApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.connectivity_api.ConnectivityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_connectivity_data_item(self):
        """Test case for create_connectivity_data_item

        """
        pass

    def test_create_connectivity_payload_item(self):
        """Test case for create_connectivity_payload_item

        """
        pass

    def test_create_connectivity_task_item(self):
        """Test case for create_connectivity_task_item

        """
        pass

    def test_delete_connectivity_task_by_id(self):
        """Test case for delete_connectivity_task_by_id

        """
        pass

    def test_get_connectivity_license(self):
        """Test case for get_connectivity_license

        """
        pass

    def test_get_connectivity_settings(self):
        """Test case for get_connectivity_settings

        """
        pass

    def test_get_connectivity_status(self):
        """Test case for get_connectivity_status

        """
        pass

    def test_get_connectivity_task_by_id(self):
        """Test case for get_connectivity_task_by_id

        """
        pass

    def test_get_connectivity_terms(self):
        """Test case for get_connectivity_terms

        """
        pass

    def test_list_connectivity_task(self):
        """Test case for list_connectivity_task

        """
        pass

    def test_update_connectivity_settings(self):
        """Test case for update_connectivity_settings

        """
        pass

    def test_update_connectivity_status(self):
        """Test case for update_connectivity_status

        """
        pass

    def test_update_connectivity_terms(self):
        """Test case for update_connectivity_terms

        """
        pass


if __name__ == '__main__':
    unittest.main()
