# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.hardening_api import HardeningApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestHardeningApi(unittest.TestCase):
    """HardeningApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.hardening_api.HardeningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_hardening_apply_item(self):
        """Test case for create_hardening_apply_item

        """
        pass

    def test_create_hardening_disable_item(self):
        """Test case for create_hardening_disable_item

        """
        pass

    def test_create_hardening_report(self):
        """Test case for create_hardening_report

        """
        pass

    def test_get_hardening_list(self):
        """Test case for get_hardening_list

        """
        pass

    def test_get_hardening_state(self):
        """Test case for get_hardening_state

        """
        pass

    def test_list_hardening_reports(self):
        """Test case for list_hardening_reports

        """
        pass


if __name__ == '__main__':
    unittest.main()
