# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.pools_pool_status_status_node import PoolsPoolStatusStatusNode  # noqa: E501
from isi_sdk.rest import ApiException


class TestPoolsPoolStatusStatusNode(unittest.TestCase):
    """PoolsPoolStatusStatusNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoolsPoolStatusStatusNode(self):
        """Test PoolsPoolStatusStatusNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.pools_pool_status_status_node.PoolsPoolStatusStatusNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
