# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.cluster_skip_optional import ClusterSkipOptional  # noqa: E501
from isi_sdk.rest import ApiException


class TestClusterSkipOptional(unittest.TestCase):
    """ClusterSkipOptional unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterSkipOptional(self):
        """Test ClusterSkipOptional"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.cluster_skip_optional.ClusterSkipOptional()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
