# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.create_providers_saml_services_cert_extract_item_response_certificate_info_value import CreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue  # noqa: E501
from isi_sdk.rest import ApiException


class TestCreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue(unittest.TestCase):
    """CreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue(self):
        """Test CreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.create_providers_saml_services_cert_extract_item_response_certificate_info_value.CreateProvidersSamlServicesCertExtractItemResponseCertificateInfoValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
