# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.providers_saml_services_sp_sp import ProvidersSamlServicesSpSp  # noqa: E501
from isi_sdk.rest import ApiException


class TestProvidersSamlServicesSpSp(unittest.TestCase):
    """ProvidersSamlServicesSpSp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvidersSamlServicesSpSp(self):
        """Test ProvidersSamlServicesSpSp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.providers_saml_services_sp_sp.ProvidersSamlServicesSpSp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
