# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.config_api import ConfigApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.config_api.ConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_config_export(self):
        """Test case for create_config_export

        """
        pass

    def test_create_config_import(self):
        """Test case for create_config_import

        """
        pass

    def test_get_config_config_lock(self):
        """Test case for get_config_config_lock

        """
        pass

    def test_get_config_export(self):
        """Test case for get_config_export

        """
        pass

    def test_get_config_import(self):
        """Test case for get_config_import

        """
        pass

    def test_list_config_exports(self):
        """Test case for list_config_exports

        """
        pass

    def test_list_config_imports(self):
        """Test case for list_config_imports

        """
        pass

    def test_update_config_config_lock(self):
        """Test case for update_config_config_lock

        """
        pass


if __name__ == '__main__':
    unittest.main()
