# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.security_api import SecurityApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestSecurityApi(unittest.TestCase):
    """SecurityApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.security_api.SecurityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_security_check_item(self):
        """Test case for create_security_check_item

        """
        pass

    def test_get_check_report(self):
        """Test case for get_check_report

        """
        pass

    def test_get_check_settings(self):
        """Test case for get_check_settings

        """
        pass

    def test_get_security_settings(self):
        """Test case for get_security_settings

        """
        pass

    def test_list_security_check(self):
        """Test case for list_security_check

        """
        pass

    def test_update_check_settings(self):
        """Test case for update_check_settings

        """
        pass

    def test_update_security_settings(self):
        """Test case for update_security_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
