# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.os_api import OsApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestOsApi(unittest.TestCase):
    """OsApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.os_api.OsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_os_security(self):
        """Test case for get_os_security

        """
        pass


if __name__ == '__main__':
    unittest.main()
