# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.cluster_mode_api import ClusterModeApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestClusterModeApi(unittest.TestCase):
    """ClusterModeApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.cluster_mode_api.ClusterModeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cluster_mode_settings(self):
        """Test case for get_cluster_mode_settings

        """
        pass

    def test_update_cluster_mode_settings(self):
        """Test case for update_cluster_mode_settings

        """
        pass


if __name__ == '__main__':
    unittest.main()
