# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.hardening_reports_report_profile_cluster_wide_rule_settings_comparisons_list_item_comparison import HardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison  # noqa: E501
from isi_sdk.rest import ApiException


class TestHardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison(unittest.TestCase):
    """HardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison(self):
        """Test HardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.hardening_reports_report_profile_cluster_wide_rule_settings_comparisons_list_item_comparison.HardeningReportsReportProfileClusterWideRuleSettingsComparisonsListItemComparison()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
