# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.create_throttling_bw_rule_response import CreateThrottlingBwRuleResponse  # noqa: E501
from isi_sdk.rest import ApiException


class TestCreateThrottlingBwRuleResponse(unittest.TestCase):
    """CreateThrottlingBwRuleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateThrottlingBwRuleResponse(self):
        """Test CreateThrottlingBwRuleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.create_throttling_bw_rule_response.CreateThrottlingBwRuleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
