# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.policy_last_job_policy_job_details import PolicyLastJobPolicyJobDetails  # noqa: E501
from isi_sdk.rest import ApiException


class TestPolicyLastJobPolicyJobDetails(unittest.TestCase):
    """PolicyLastJobPolicyJobDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyLastJobPolicyJobDetails(self):
        """Test PolicyLastJobPolicyJobDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.policy_last_job_policy_job_details.PolicyLastJobPolicyJobDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
