# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.models.datamover_account_credentials_certificate_extended import DatamoverAccountCredentialsCertificateExtended  # noqa: E501
from isi_sdk.rest import ApiException


class TestDatamoverAccountCredentialsCertificateExtended(unittest.TestCase):
    """DatamoverAccountCredentialsCertificateExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatamoverAccountCredentialsCertificateExtended(self):
        """Test DatamoverAccountCredentialsCertificateExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = isi_sdk.models.datamover_account_credentials_certificate_extended.DatamoverAccountCredentialsCertificateExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
