# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import isi_sdk
from isi_sdk.api.network_firewall_api import NetworkFirewallApi  # noqa: E501
from isi_sdk.rest import ApiException


class TestNetworkFirewallApi(unittest.TestCase):
    """NetworkFirewallApi unit test stubs"""

    def setUp(self):
        self.api = isi_sdk.api.network_firewall_api.NetworkFirewallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policies_policy_rule(self):
        """Test case for create_policies_policy_rule

        """
        pass

    def test_delete_policies_policy_rule(self):
        """Test case for delete_policies_policy_rule

        """
        pass

    def test_get_policies_policy_rule(self):
        """Test case for get_policies_policy_rule

        """
        pass

    def test_list_policies_policy_rules(self):
        """Test case for list_policies_policy_rules

        """
        pass

    def test_update_policies_policy_rule(self):
        """Test case for update_policies_policy_rule

        """
        pass


if __name__ == '__main__':
    unittest.main()
