# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from isi_sdk.configuration import Configuration


class CloudProxyExtended(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'password_is_set': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'password_is_set': 'password_is_set'
    }

    def __init__(self, id=None, password_is_set=None, _configuration=None):  # noqa: E501
        """CloudProxyExtended - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._password_is_set = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if password_is_set is not None:
            self.password_is_set = password_is_set

    @property
    def id(self):
        """Gets the id of this CloudProxyExtended.  # noqa: E501

        A globally unique ID (guid) or the name of this proxy (read-only)  # noqa: E501

        :return: The id of this CloudProxyExtended.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CloudProxyExtended.

        A globally unique ID (guid) or the name of this proxy (read-only)  # noqa: E501

        :param id: The id of this CloudProxyExtended.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def password_is_set(self):
        """Gets the password_is_set of this CloudProxyExtended.  # noqa: E501

        Indicates whether a password has been set for this proxy  # noqa: E501

        :return: The password_is_set of this CloudProxyExtended.  # noqa: E501
        :rtype: bool
        """
        return self._password_is_set

    @password_is_set.setter
    def password_is_set(self, password_is_set):
        """Sets the password_is_set of this CloudProxyExtended.

        Indicates whether a password has been set for this proxy  # noqa: E501

        :param password_is_set: The password_is_set of this CloudProxyExtended.  # noqa: E501
        :type: bool
        """

        self._password_is_set = password_is_set

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudProxyExtended, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudProxyExtended):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CloudProxyExtended):
            return True

        return self.to_dict() != other.to_dict()
