# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from isi_sdk.configuration import Configuration


class FilepoolPolicyCreateParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_matching_pattern': 'FilepoolPolicyFileMatchingPattern',
        'name': 'str'
    }

    attribute_map = {
        'file_matching_pattern': 'file_matching_pattern',
        'name': 'name'
    }

    def __init__(self, file_matching_pattern=None, name=None, _configuration=None):  # noqa: E501
        """FilepoolPolicyCreateParams - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file_matching_pattern = None
        self._name = None
        self.discriminator = None

        self.file_matching_pattern = file_matching_pattern
        self.name = name

    @property
    def file_matching_pattern(self):
        """Gets the file_matching_pattern of this FilepoolPolicyCreateParams.  # noqa: E501

        The file matching rules for this policy.  # noqa: E501

        :return: The file_matching_pattern of this FilepoolPolicyCreateParams.  # noqa: E501
        :rtype: FilepoolPolicyFileMatchingPattern
        """
        return self._file_matching_pattern

    @file_matching_pattern.setter
    def file_matching_pattern(self, file_matching_pattern):
        """Sets the file_matching_pattern of this FilepoolPolicyCreateParams.

        The file matching rules for this policy.  # noqa: E501

        :param file_matching_pattern: The file_matching_pattern of this FilepoolPolicyCreateParams.  # noqa: E501
        :type: FilepoolPolicyFileMatchingPattern
        """
        if self._configuration.client_side_validation and file_matching_pattern is None:
            raise ValueError("Invalid value for `file_matching_pattern`, must not be `None`")  # noqa: E501

        self._file_matching_pattern = file_matching_pattern

    @property
    def name(self):
        """Gets the name of this FilepoolPolicyCreateParams.  # noqa: E501

        A unique name for this policy.  # noqa: E501

        :return: The name of this FilepoolPolicyCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FilepoolPolicyCreateParams.

        A unique name for this policy.  # noqa: E501

        :param name: The name of this FilepoolPolicyCreateParams.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 768):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `768`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilepoolPolicyCreateParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilepoolPolicyCreateParams):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FilepoolPolicyCreateParams):
            return True

        return self.to_dict() != other.to_dict()
