# coding: utf-8

"""
    Isilon SDK

    Isilon SDK - Language bindings for the OneFS API  # noqa: E501

    OpenAPI spec version: 22
    Contact: sdk@isilon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from isi_sdk.configuration import Configuration


class KmipServerCreateParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ca_cert_path': 'str',
        'client_cert_path': 'str',
        'host': 'str',
        'id': 'str'
    }

    attribute_map = {
        'ca_cert_path': 'ca_cert_path',
        'client_cert_path': 'client_cert_path',
        'host': 'host',
        'id': 'id'
    }

    def __init__(self, ca_cert_path=None, client_cert_path=None, host=None, id=None, _configuration=None):  # noqa: E501
        """KmipServerCreateParams - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ca_cert_path = None
        self._client_cert_path = None
        self._host = None
        self._id = None
        self.discriminator = None

        self.ca_cert_path = ca_cert_path
        self.client_cert_path = client_cert_path
        self.host = host
        self.id = id

    @property
    def ca_cert_path(self):
        """Gets the ca_cert_path of this KmipServerCreateParams.  # noqa: E501

        Certification Authority (CA) certificate, used for TLS Mutual Authentication with the KMIP Server.  # noqa: E501

        :return: The ca_cert_path of this KmipServerCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._ca_cert_path

    @ca_cert_path.setter
    def ca_cert_path(self, ca_cert_path):
        """Sets the ca_cert_path of this KmipServerCreateParams.

        Certification Authority (CA) certificate, used for TLS Mutual Authentication with the KMIP Server.  # noqa: E501

        :param ca_cert_path: The ca_cert_path of this KmipServerCreateParams.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ca_cert_path is None:
            raise ValueError("Invalid value for `ca_cert_path`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ca_cert_path is not None and len(ca_cert_path) > 4096):
            raise ValueError("Invalid value for `ca_cert_path`, length must be less than or equal to `4096`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ca_cert_path is not None and len(ca_cert_path) < 1):
            raise ValueError("Invalid value for `ca_cert_path`, length must be greater than or equal to `1`")  # noqa: E501

        self._ca_cert_path = ca_cert_path

    @property
    def client_cert_path(self):
        """Gets the client_cert_path of this KmipServerCreateParams.  # noqa: E501

        Cluster identity certificate and private key used for TLS Mutual Authentication with the KMIP Server.  # noqa: E501

        :return: The client_cert_path of this KmipServerCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._client_cert_path

    @client_cert_path.setter
    def client_cert_path(self, client_cert_path):
        """Sets the client_cert_path of this KmipServerCreateParams.

        Cluster identity certificate and private key used for TLS Mutual Authentication with the KMIP Server.  # noqa: E501

        :param client_cert_path: The client_cert_path of this KmipServerCreateParams.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and client_cert_path is None:
            raise ValueError("Invalid value for `client_cert_path`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                client_cert_path is not None and len(client_cert_path) > 4096):
            raise ValueError("Invalid value for `client_cert_path`, length must be less than or equal to `4096`")  # noqa: E501
        if (self._configuration.client_side_validation and
                client_cert_path is not None and len(client_cert_path) < 1):
            raise ValueError("Invalid value for `client_cert_path`, length must be greater than or equal to `1`")  # noqa: E501

        self._client_cert_path = client_cert_path

    @property
    def host(self):
        """Gets the host of this KmipServerCreateParams.  # noqa: E501

        KMIP server hostname.  # noqa: E501

        :return: The host of this KmipServerCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this KmipServerCreateParams.

        KMIP server hostname.  # noqa: E501

        :param host: The host of this KmipServerCreateParams.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                host is not None and len(host) > 256):
            raise ValueError("Invalid value for `host`, length must be less than or equal to `256`")  # noqa: E501
        if (self._configuration.client_side_validation and
                host is not None and len(host) < 1):
            raise ValueError("Invalid value for `host`, length must be greater than or equal to `1`")  # noqa: E501

        self._host = host

    @property
    def id(self):
        """Gets the id of this KmipServerCreateParams.  # noqa: E501

        Unique KMIP server identifier.  # noqa: E501

        :return: The id of this KmipServerCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this KmipServerCreateParams.

        Unique KMIP server identifier.  # noqa: E501

        :param id: The id of this KmipServerCreateParams.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                id is not None and len(id) > 64):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `64`")  # noqa: E501
        if (self._configuration.client_side_validation and
                id is not None and len(id) < 1):
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501
        if (self._configuration.client_side_validation and
                id is not None and not re.search(r'^[a-zA-Z0-9_-]+$', id)):  # noqa: E501
            raise ValueError(r"Invalid value for `id`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KmipServerCreateParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KmipServerCreateParams):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KmipServerCreateParams):
            return True

        return self.to_dict() != other.to_dict()
